name: sml-practical-env
channels:
  - conda-forge
dependencies:
  - anaconda=2024.02
  - python=3.10
  - numpy=1.26.4
  - pandas=2.1.4
  - scikit-learn=1.3.0
  - scikit-plot
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - scipy=1.11.4
  - pytorch=2.2
  - xgboost=1.7.3
  - optuna=3.5.0